print('Welcome to the Mad Lib Generator!')
print('Please type in a word when prompted.')
print('')
adjective1 = raw_input('Type in an adjective: ')
adjective2 = raw_input('Give us another adjective: ')
adjective3 = raw_input('And another adjective: ')
adjective4 = raw_input('And one last adjective please: ')
woman_name = raw_input("A woman musician's name: ")
plural_animals = raw_input('Animal (pluarl): ')
beverage = raw_input('A hot beverage: ')
exclamation = raw_input('An exclamation: ')
verb_break = raw_input('A verb: ')
body_part = raw_input('A body part (plural): ')
print('')
print("Here's your story")
print('')
print('There once was a ' + adjective1 + ' programmer named ' + woman_name)
print('who wanted to build a ' + adjective2 + ' mobile app to')
print('help ' + adjective3 + ' ' + plural_animals + ' find new homes.')
print('')
print(woman_name + ' stayed up all night, drinking lots of')
print('caffeinated ' + beverage + ' as she worked and worked')
print('trying to complete her ' + adjective4 + ' program.')
print('')
print('Whenever ' + woman_name + ' hit a dead end, she would')
print('exclaim *' +exclamation +'*!')
print('')
print('But she was not discouraged, and after a quick break')
print('to ' + verb_break + ' and clear her head, she got back to work.')
print('')
print('By morning, when the sun started to rise, she let out a')
print('big yawn and stretched her ' + body_part + '.')
print('Finally, she was done.')
